// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.oficios.domain;

import ar.edu.um.oficios.domain.Oficio;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Oficio_Roo_Configurable {
    
    declare @type: Oficio: @Configurable;
    
}
