// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.oficios.domain;

import ar.edu.um.oficios.domain.Oficio;

privileged aspect Oficio_Roo_JavaBean {
    
    public String Oficio.getNombre() {
        return this.nombre;
    }
    
    public void Oficio.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
